version: "3"
services:
  database:
    container_name: database
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_USER: "your_day_db_user"
      POSTGRES_PASSWORD: "your_day_db_password"
      POSTGRES_DB: YourDayDB
    ports:
      - "5432:5432"
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - db-data:/var/lib/backup/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  #backend:
  #  container_name: backend
  #  depends_on:
  #    database:
  #      condition: service_healthy
  #  ports:
  #    - "5000:5000"
  #  build: ./backend
  #  env_file:
  #   - .env
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-size: "10m"


volumes:
  db-data:

    
  
  
